---
title: "BST222 Project"
author: "Yunyang Zhong, Tianxiu Li(Katherine), Linfeng Hu"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

## Data Exploration

```{r}
library(tidyverse)

data<-read.csv("us.csv")
```

```{r}
data %>% 
  filter(State=="MA") %>% 
  mutate(Year=substring(Start_Time,1,4)) %>% 
  mutate(Month=substring(Start_Time, 6,7)) %>% 
  group_by(Year) %>% 
  count()
```

```{r}
data %>% 
  filter(State=="MA") %>% 
  mutate(Year=substring(Start_Time,1,4)) %>% 
  group_by(Year) %>% 
  count() %>% 
  ggplot(aes(x = n)) +
  geom_density()
```

```{r}
count <- c(820,875,827,691,2363,816)
mean(count)
sd(count)

count_1 <- c(820,875,827,691,816)
mean(count_1)
sd(count_1)
```

## Simulation

```{r}
set.seed(222)
library(data.table)
library(dplyr)
results <- rbindlist(lapply(1:1000, function(i){
  rbindlist(lapply(c(50, 100, 500, 1000, 5000), function(n){
  rbindlist(lapply(c(770, 790, 810, 830, 850, 870), function(param){
    x_pois <- round(rpois(n, param))
    
    # calculate lambda hat
    MLE_pois <- sum(x_pois)/n
    # calculate true probability at cutoff
    trueProb <- ppois(816, param)
    
    par_MLE <- ppois(816, MLE_pois)
    par_CNT <- sum(x_pois <= 816)/n
  
    
    # return estimates in data table
    data.table(n = c(n, n),
               estimator = factor(c("MLE", "CNT")),
               param_mu = c(param, param),
               trueProb = c(trueProb, trueProb), 
               prob = c(par_MLE, par_CNT)
               )
  }))
  }))
}))
options(scipen = 999)
results <- results %>%
  mutate_if(is.numeric, round, digits=3) %>%
  arrange(n, param_mu)
results
results|>filter(n==50,estimator=="MLE",param_mu==810)|>summarise(mean=mean(prob))
```


## Evaluation

#### Bias

```{r}
# Get results from simulation
bias_sim = results[, .(mean_bias = mean(prob - trueProb)), by = c("n", "param_mu", "estimator")]
head(bias_sim)
library(ggplot2)
library(dplyr)
# Plot of bias, facet by lambda
bias_sim %>%
  ggplot(aes(x = n, y = mean_bias, color = estimator)) + 
  geom_point() + geom_line(alpha=0.5) +
  #geom_point(aes(shape = factor(param_mu))) +
  geom_abline(slope = 0, intercept = 0, alpha = 0.2) + 
  facet_wrap(~ param_mu) +
  labs(x = "Sample size", y = "Mean bias") +
  theme_classic()
```

#### MSE

```{r}
mse_sim <- results[, .(mean_mse = mean(var(prob)+ (prob - trueProb)^2)), by = c("n", "param_mu", "estimator")]
head(mse_sim)
# Plot of MSE, facet by lambda
mse_sim %>%
  ggplot(aes(x = n, y = mean_mse, color = estimator)) +
  geom_point() + geom_line(alpha = 0.2) +
  scale_shape_discrete("True value") +
  geom_abline(slope = 0, intercept = 0, alpha = 0.1) +
  facet_wrap(~ param_mu) +
  labs(x = "Sample size", y = "Mean Squared Error") +
  theme_classic()
```

#### Variance

```{r}
estimator_var <- results[, .(var_est = mean(var(prob))), 
                         by = c("n", "param_mu", "estimator")]
head(estimator_var)
# Plot of variance
estimator_var %>%
  ggplot(aes(x = n, y = var_est, color = estimator)) +
  geom_line(alpha = 0.5) +
  geom_point() + 
  geom_abline(slope = 0, intercept = 0, alpha = 0.2) +
  facet_wrap(~param_mu) +
  labs(x = "Sample size", y = "Variance") +
  theme_classic()
```
